### ISSUE TITLE
The workflow runs on all closed PRs

### ISSUE THREAD

**Issue by HaloKo4** [asaaki/gha-delete-unmerged-branches#3]
@asaaki  hi
currently the code runs on all closed PRs including merged one.
yes for merged it doesn't do anything but we can still see the action triggered which is a waste (and spam)
how we can limit the action to run only on closed PR who were not merged?

**Comment by asaaki** [comment]
Hi @HaloKo4,

as far as I know this is a limitation in GitHub's workflow event triggers.
As you can see under ["Events that trigger workflows" > `pull_request`][1], there are not specific triggers for merged vs unmerged, only a generic closed event.

You could try to dig into the event payload (see ["Webhook events and payloads" > `pull_request`][2]) and try to formulate an `if` statement like

```yaml
# snip
jobs:
  worker:
    # maybe empty string instead:
    #       github.event.pull_request.merged_at == ''
    if: ${{ github.event.pull_request.merged_at == null}}
    runs-on: ubuntu-latest
    steps:
      #snip
```

but I haven't tested that.

If you would give it a try and report back (maybe even as a pull request?), that would be awesome. 

[1]: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
[2]: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
